In [1]:
# Import Dependencies
import numpy as np 
import pandas as pd

In [2]:
# Import csv data
chilis_data = pd.read_csv('Menus/Chilis.csv')
chilis = chilis_data.copy()
dataset = chilis_data.copy()
chilis_data

,dish_name,cross_contam,egg,fish,cow_milk,peanut,shellfish,soy,tree_nuts,gluten,veg/vgn,dish_type
0,Awesome Blossom Petals,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,VT,App
1,Boneless Wings - Buffalo,1.0,1.0,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,App
2,Boneless Wings - Honey Chipotle,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,App
3,Boneless Wings - House BBQ,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,App
4,Boneless Wings - Mango-Habanero,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,App
...,...,...,...,...,...,...,...,...,...,...,...,...
231,Honey Chipotle Sauce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VT,add_ons
232,Pickles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VG,add_ons
233,Salsa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VG,add_ons
234,Sour Cream,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,VT,add_ons
235,Wing Sauce,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,add_ons

In [3]:
# Dish Data ETL Function
def allergenETL(dataset):
    #Restaurant Name Modification
    dataset['restaurant_name'] = "Chili's"
    dataset['restaurant_id'] = 1
    dataset['dish_id'] = 0
    
    # Ensure all columns are present and are FALSE if not present
    column_names = dataset.columns.values.tolist()
   
    # Change 1.0 to TRUE
    for column in column_names:
        dataset[column] = np.where((dataset[column] == 1.0), True, dataset[column])

     # Change 1.0 to TRUE
    for column in column_names:
        if dataset[column].dtype == float:
            dataset[column] = dataset[column].astype(object)
            dataset[column] = np.where((dataset[column] == 1.0), True, dataset[column])
            dataset[column] = dataset[column].fillna(False)
            dataset[column] = dataset[column].astype(bool)

    # Define column types: 
    all_cols = ['dish_id', 'dish_name', 'restaurant_id', 'restaurant_name', 'dish_type', 'ingredients', 'modifiable', 'cross_contam', 'vegan', 'vegetarian', 'gluten', 'dairy', 'tree_nuts', 'seeds', 'nightshades', 'egg', 'fish', 'peanut', 'shellfish', 'molllusks', 'legumes', 'garlic', 'soy', 'corn', 'wheat', 'barley', 'rye', 'sesame', 'coffee', 'buckwheat', 'lupin', 'mustard', 'celery', 'oat', 'rice', 'acerloa', 'apple', 'apricot', 'banana', 'cherry',	'dates', 'fig', 'grape', 'kiwi', 'lychee', 'mango', 'melon', 'orange', 'peach', 'pear', 'persimmon', 'pineapple', 'pomegranate', 'prune', 'strawberry', 'tomato', 'chickpea', 'lentil', 'pea', 'asparagus', 'avocado', 'bell_pepper', 'cabbage', 'carrot', 'lettuce', 'potato', 'pumpkin', 'turnip', 'zucchini', 'almond', 'brazil_nut', 'cashew', 'chestnut', 'hazelnut', 'macadamia', 'pecan', 'pine_nut', 'pistachio', 'walnut', 'mustard_seed', 'poppy_seed', 'pumpkin_seed', 'sunflower_seed', 'cow_milk', 'goat_milk', 'sheep_milk', 'alaska_pollack', 'carp', 'cod', 'dogfish', 'mackeral', 'salmon', 'sole', 'tuna','crustacean', 'crab', 'lobster', 'shrimp', 'abalone', 'horned_turban', 'limpet', 'marine_snail', 'mussel', 'octopus', 'oyster', 'scallop', 'squid', 'whelk', 'beef', 'chicken', 'frog', 'honey', 'mushroom', 'mycoprotein']

    # Boolean columns
    bool_cols = ['modifiable', 'cross_contam', 'vegan', 'vegetarian', 'gluten', 'dairy', 'tree_nuts', 'seeds', 'nightshades', 'egg', 'fish', 'peanut', 'shellfish', 'molllusks', 'legumes', 'garlic', 'soy', 'corn', 'wheat', 'barley', 'rye', 'sesame', 'coffee', 'buckwheat', 'lupin', 'mustard', 'celery', 'oat', 'rice', 'acerloa', 'apple', 'apricot', 'banana', 'cherry',	'dates', 'fig', 'grape', 'kiwi', 'lychee', 'mango', 'melon', 'orange', 'peach', 'pear', 'persimmon', 'pineapple', 'pomegranate', 'prune', 'strawberry', 'tomato', 'chickpea', 'lentil', 'pea', 'asparagus', 'avocado', 'bell_pepper', 'cabbage', 'carrot', 'lettuce', 'potato', 'pumpkin', 'turnip', 'zucchini', 'almond', 'brazil_nut', 'cashew', 'chestnut', 'hazelnut', 'macadamia', 'pecan', 'pine_nut', 'pistachio', 'walnut', 'mustard_seed', 'poppy_seed', 'pumpkin_seed', 'sunflower_seed', 'cow_milk', 'goat_milk', 'sheep_milk', 'alaska_pollack', 'carp', 'cod', 'dogfish', 'mackeral', 'salmon', 'sole', 'tuna','crustacean', 'crab', 'lobster', 'shrimp', 'abalone', 'horned_turban', 'limpet', 'marine_snail', 'mussel', 'octopus', 'oyster', 'scallop', 'squid', 'whelk', 'beef', 'chicken', 'frog', 'honey', 'mushroom', 'mycoprotein'] 

    # Integer columns
    int_cols = ['dish_id', 'restaurant_id']

    # Object columns
    obj_cols = ['dish_name', 'restaurant_name', 'dish_type', 'ingredients']

    # Create the missing columns with the correct types
    for column in bool_cols:
        if column not in column_names:
            dataset[column] = False
        else: pass
    
    # for column in int_cols:
    #     if column not in column_names:
    #      dataset[column].astype(int)
    #     #  dataset[column] = pd.to_numeric(dataset[column], downcast = 'integer')
    #     #  dataset[column] = dataset[column].astype(int, errors='raise')
    #     else: pass

    for column in obj_cols:
        if column not in column_names:
            dataset[column] = ''
            dataset[column].astype(object)
        else: pass

    # # Expanding Vegetarian/Vegan
    dataset['vegetarian'] = np.where((dataset['veg/vgn'] == 'VT'), True, False)
    dataset['vegan'] = np.where((dataset['veg/vgn'] == 'VG'), True, False)
    dropthese = ['veg/vgn']
    dataset = dataset.drop(columns = dropthese, axis=1)

    # Order Columns
    dataset = dataset[all_cols]

    return dataset

In [4]:
chilis = chilis_data.copy()
data = allergenETL(chilis)
data

,dish_id,dish_name,restaurant_id,restaurant_name,dish_type,ingredients,modifiable,cross_contam,vegan,vegetarian,...,oyster,scallop,squid,whelk,beef,chicken,frog,honey,mushroom,mycoprotein
0,0,Awesome Blossom Petals,1,Chili's,App,,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,0,Boneless Wings - Buffalo,1,Chili's,App,,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0,Boneless Wings - Honey Chipotle,1,Chili's,App,,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,Boneless Wings - House BBQ,1,Chili's,App,,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0,Boneless Wings - Mango-Habanero,1,Chili's,App,,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,0,Honey Chipotle Sauce,1,Chili's,add_ons,,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
232,0,Pickles,1,Chili's,add_ons,,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
233,0,Salsa,1,Chili's,add_ons,,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
234,0,Sour Cream,1,Chili's,add_ons,,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
235,0,Wing Sauce,1,Chili's,add_ons,,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
data.info(verbose=True)
data.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 114 columns):
 #   Column           Dtype
---  ------           -----
 0   dish_id          int64
 1   dish_name        object
 2   restaurant_id    int64
 3   restaurant_name  object
 4   dish_type        object
 5   ingredients      object
 6   modifiable       bool
 7   cross_contam     bool
 8   vegan            bool
 9   vegetarian       bool
 10  gluten           bool
 11  dairy            bool
 12  tree_nuts        bool
 13  seeds            bool
 14  nightshades      bool
 15  egg              bool
 16  fish             bool
 17  peanut           bool
 18  shellfish        bool
 19  molllusks        bool
 20  legumes          bool
 21  garlic           bool
 22  soy              bool
 23  corn             bool
 24  wheat            bool
 25  barley           bool
 26  rye              bool
 27  sesame           bool
 28  coffee           bool
 29  buckwheat        bool
 30  lupin            bool
 31  mustard          bool
 32  celery           bool
 33  oat              bool
 34  rice             bool
 35  acerloa          bool
 36  apple            bool
 37  apricot          bool
 38  banana           bool
 39  cherry           bool
 40  dates            bool
 41  fig              bool
 42  grape            bool
 43  kiwi             bool
 44  lychee           bool
 45  mango            bool
 46  melon            bool
 47  orange           bool
 48  peach            bool
 49  pear             bool
 50  persimmon        bool
 51  pineapple        bool
 52  pomegranate      bool
 53  prune            bool
 54  strawberry       bool
 55  tomato           bool
 56  chickpea         bool
 57  lentil           bool
 58  pea              bool
 59  asparagus        bool
 60  avocado          bool
 61  bell_pepper      bool
 62  cabbage          bool
 63  carrot           bool
 64  lettuce          bool
 65  potato           bool
 66  pumpkin          bool
 67  turnip           bool
 68  zucchini         bool
 69  almond           bool
 70  brazil_nut       bool
 71  cashew           bool
 72  chestnut         bool
 73  hazelnut         bool
 74  macadamia        bool
 75  pecan            bool
 76  pine_nut         bool
 77  pistachio        bool
 78  walnut           bool
 79  mustard_seed     bool
 80  poppy_seed       bool
 81  pumpkin_seed     bool
 82  sunflower_seed   bool
 83  cow_milk         bool
 84  goat_milk        bool
 85  sheep_milk       bool
 86  alaska_pollack   bool
 87  carp             bool
 88  cod              bool
 89  dogfish          bool
 90  mackeral         bool
 91  salmon           bool
 92  sole             bool
 93  tuna             bool
 94  crustacean       bool
 95  crab             bool
 96  lobster          bool
 97  shrimp           bool
 98  abalone          bool
 99  horned_turban    bool
 100 limpet           bool
 101 marine_snail     bool
 102 mussel           bool
 103 octopus          bool
 104 oyster           bool
 105 scallop          bool
 106 squid            bool
 107 whelk            bool
 108 beef             bool
 109 chicken          bool
 110 frog             bool
 111 honey            bool
 112 mushroom         bool
 113 mycoprotein      bool
dtypes: bool(108), int64(2), object(4)
memory usage: 36.1+ KB

dish_id             int64
dish_name          object
restaurant_id       int64
restaurant_name    object
dish_type          object
                    ...
chicken              bool
frog                 bool
honey                bool
mushroom             bool
mycoprotein          bool
Length: 114, dtype: object

In [6]:
output_file = "Menus/chilis_data_final1.csv"
data.to_csv(output_file, index = False)

In [7]:
chilis_final = pd.read_csv('Menus/chilis_data_final.csv')
chilis_final

,dish_id,dish_name,restaurant_id,restaurant_name,dish_type,ingredients,modifiable,cross_contam,vegan,vegetarian,...,oyster,scallop,squid,whelk,beef,chicken,frog,honey,mushroom,mycoprotein
0,1,Awesome Blossom Petals,1,Chili's,App,NaN,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,2,Boneless Wings - Buffalo,1,Chili's,App,NaN,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,Boneless Wings - Honey Chipotle,1,Chili's,App,NaN,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,4,Boneless Wings - House BBQ,1,Chili's,App,NaN,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5,Boneless Wings - Mango-Habanero,1,Chili's,App,NaN,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,232,Honey Chipotle Sauce,1,Chili's,add_ons,NaN,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
232,233,Pickles,1,Chili's,add_ons,NaN,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
233,234,Salsa,1,Chili's,add_ons,NaN,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
234,235,Sour Cream,1,Chili's,add_ons,NaN,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
235,236,Wing Sauce,1,Chili's,add_ons,NaN,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
chilis_final.dtypes

dish_id             int64
dish_name          object
restaurant_id       int64
restaurant_name    object
dish_type          object
                    ...
chicken              bool
frog                 bool
honey                bool
mushroom             bool
mycoprotein          bool
Length: 114, dtype: object